%% Color Segmentation using GGM model
% Estimate probabilites of test image pixels in the test image

    test_im_rgb = imread([test_dir_name, imdir(cur_im).name]);
    num_pix = size(test_im_rgb,1)*size(test_im_rgb,2);
    test_im = rgb2ycbcr(test_im_rgb);
    y_test = reshape(test_im, [num_pix,3]);

    [n,d] = size(y_test);
    probs_r = sum(repmat(w_b, n, 1).*gaussian_model(double(y_test), mu_b, SIGMA_b), 2);%find pixels with a high probability of being generated by a gaussian
    probs_o = sum(repmat(w_o, n, 1).*gaussian_model(double(y_test), mu_o, SIGMA_o), 2);%find pixels with a high probability of being generated by a gaussian
    red_inds = find(probs_r > probs_o);

    red_mask = zeros(size(test_im(:,:,1)));
    red_mask(red_inds)=1;
    
    %Some morphology to clean up the mask
    SE = strel('square',15);
    red_mask2 = imerode(red_mask, SE);
    SE2 = strel('square', 20);
    red_mask2 = imdilate(red_mask2, SE2);
    
%     figure(99);
%     subplot(2,1,1);  
%     imshow(red_mask);
%     subplot(2,1,2);
%     imshow(red_mask2);
%     title(imdir(i).name);

    red_mask = red_mask2;
    
