function [barrel_dist_func, gof] = fit_barrel_dist_func(barrel_width_lut, one2ten)
%CREATEFIT(BARREL_WIDTH_LUT,ONE2TEN)
%  Create a fit.
%
%  Data for 'barrel_dist' fit:
%      X Input : barrel_width_lut
%      Y Output: one2ten
%  Output:
%      barrel_dist_func : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jan-2015 02:16:32


%% Fit: 'barrel_dist'.
[xData, yData] = prepareCurveData( barrel_width_lut, one2ten );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [18.2644447568488 -0.0152685640206501 1.3774665400745 -0.00057587603115006];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'barrel_dist' );
h = plot( fitresult, xData, yData );
legend( h, 'one2ten vs. barrel_width_lut', 'barrel_dist', 'Location', 'NorthEast' );
% Label axes
xlabel barrel_width_lut
ylabel one2ten
grid on


